# Generated by Django 5.2.6 on 2026-01-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellules', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('type_contact', models.CharField(max_length=50)),
                ('remarque', models.CharField(blank=True, max_length=100)),
                ('id_cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellules.cellule')),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
            ],
        ),
    ]
