# Generated by Django 5.2.7 on 2026-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_contact', models.CharField(choices=[('ENTREPRISE', 'Entreprise'), ('PARTENAIRE', 'Partenaire'), ('INTERVENANT', 'Intervenant')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('derniere_interaction', models.DateField(auto_now=True)),
            ],
        ),
    ]
