# Generated by Django 5.2.7 on 2026-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_cellule',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id_membre',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='remarque',
        ),
        migrations.AddField(
            model_name='contact',
            name='derniere_interaction',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.CharField(choices=[('ENTREPRISE', 'Entreprise'), ('PARTENAIRE', 'Partenaire'), ('INTERVENANT', 'Intervenant')], max_length=20),
        ),
    ]
