# Generated by Django 5.2.6 on 2026-01-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id_cellule', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cellule', models.CharField(max_length=50)),
            ],
        ),
    ]
