# Generated by Django 5.2.6 on 2026-01-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='membres.membre')),
                ('id_membre_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='membres.membre')),
            ],
        ),
    ]
