# Generated by Django 5.2.7 on 2026-01-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_cellule_remove_membre_id_cellule_profil'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='membres.profil'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_membre_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='membres.profil'),
        ),
    ]
