# Generated by Django 5.2.6 on 2026-01-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('id_cellule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellules.cellule')),
            ],
        ),
    ]
