# Generated by Django 5.2.7 on 2026-01-22 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='id_cellule',
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('CHEF', 'Chef de Cellule'), ('RESPONSABLE', 'Responsable'), ('MEMBRE', 'Membre Actif')], default='MEMBRE', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('cellule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='membres.cellule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
