# Generated by Django 5.2.7 on 2026-01-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_alter_evenement_participants'),
        ('membres', '0002_cellule_remove_membre_id_cellule_profil'),
        ('messagerie', '0002_alter_message_id_membre_alter_message_id_membre_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
