# Generated by Django 5.2.7 on 2026-01-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('categorie', models.CharField(choices=[('REUNION', 'Réunion'), ('FORMATION', 'Formation'), ('EVENEMENT', 'Événement'), ('AUTRE', 'Autre')], default='EVENEMENT', max_length=20)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to='membres.profil')),
                ('participants', models.ManyToManyField(blank=True, related_name='evenements_participe', to='membres.profil')),
            ],
        ),
    ]
