# Generated by Django 5.2.7 on 2026-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
        ('membres', '0002_cellule_remove_membre_id_cellule_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(related_name='evenements_participe', to='membres.profil'),
        ),
    ]
