# Generated by Django 5.2.7 on 2026-01-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id_membre',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_membre_1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='type_message',
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='membres.profil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envoyes', to='membres.profil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='message',
            name='objet',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
